apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: productpage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: productpage-v#{ContainerVersion}#
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: productpage
        version: v#{ContainerVersion}#
    spec:
      containers:
      - name: productpage
        image: hjgraca.azurecr.io/productpage:#{ContainerVersion}#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080