apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reviews-v#{ContainerVersion}#
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reviews
        version: v#{ContainerVersion}#
    spec:
      containers:
      - name: reviews
        image: hjgraca.azurecr.io/reviews:#{ContainerVersion}#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080